require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/passwords", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Password. As you add validations to Password, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Password.create! valid_attributes
      get passwords_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      password = Password.create! valid_attributes
      get password_url(password)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_password_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      password = Password.create! valid_attributes
      get edit_password_url(password)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Password" do
        expect {
          post passwords_url, params: { password: valid_attributes }
        }.to change(Password, :count).by(1)
      end

      it "redirects to the created password" do
        post passwords_url, params: { password: valid_attributes }
        expect(response).to redirect_to(password_url(Password.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Password" do
        expect {
          post passwords_url, params: { password: invalid_attributes }
        }.to change(Password, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post passwords_url, params: { password: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested password" do
        password = Password.create! valid_attributes
        patch password_url(password), params: { password: new_attributes }
        password.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the password" do
        password = Password.create! valid_attributes
        patch password_url(password), params: { password: new_attributes }
        password.reload
        expect(response).to redirect_to(password_url(password))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        password = Password.create! valid_attributes
        patch password_url(password), params: { password: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested password" do
      password = Password.create! valid_attributes
      expect {
        delete password_url(password)
      }.to change(Password, :count).by(-1)
    end

    it "redirects to the passwords list" do
      password = Password.create! valid_attributes
      delete password_url(password)
      expect(response).to redirect_to(passwords_url)
    end
  end
end
